import React, { useState, useEffect } from 'react';
import './Home.css';

const Home = () => {
  const [time, setTime] = useState(new Date());
  const [isAnalog, setIsAnalog] = useState(false); // State to toggle format

  useEffect(() => {
    const timer = setInterval(() => setTime(new Date()), 1000); // Update every second for smooth hands
    return () => clearInterval(timer);
  }, []);

  // Digital formatting helpers
  const formatDigital = () => {
    return time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: true });
  };

  // Analog hand calculations (Degrees)
  const secondsDeg = (time.getSeconds() / 60) * 360;
  const minutesDeg = (time.getMinutes() / 60) * 360 + (time.getSeconds() / 60) * 6;
  const hoursDeg = (time.getHours() / 12) * 360 + (time.getMinutes() / 60) * 30;

  return (
    <div className="nexus-home-container">
      <main className="nexus-dashboard-main">
        <div className="header-row">
          <h1 className="greeting">Good Evening</h1>
          
          {/* THE TOGGLE SWITCH */}
          <div className="toggle-container">
            <span>Digital</span>
            <label className="switch">
              <input type="checkbox" onChange={() => setIsAnalog(!isAnalog)} />
              <span className="slider round"></span>
            </label>
            <span>Analog</span>
          </div>
        </div>
        
        <div className="ai-summary-card">
          <div className="summary-content">
            <div className="clock-section">
              <div className="clock-circle">
                {isAnalog ? (
                  /* ANALOG FORMAT */
                  <div className="analog-clock">
                    <div className="hand hour" style={{ transform: `rotate(${hoursDeg}deg)` }}></div>
                    <div className="hand minute" style={{ transform: `rotate(${minutesDeg}deg)` }}></div>
                    <div className="hand second" style={{ transform: `rotate(${secondsDeg}deg)` }}></div>
                    <div className="center-dot"></div>
                  </div>
                ) : (
                  /* DIGITAL FORMAT */
                  <span className="current-time">
                    {formatDigital().replace(/[a-zA-Z]|\s/g, '')}
                    <small>{time.getHours() >= 12 ? 'PM' : 'AM'}</small>
                  </span>
                )}
              </div>
            </div>
            
            <div className="text-section">
              <h3>Nexus Summary</h3>
              <p className="activity-label">Here's your activity for today:</p>
              <ul className="activity-list">
                <li>✓ You received 12 messages across 4 chats.</li>
                <li>✓ Your most active chat was with Alex.</li>
                <li>✓ You missed 2 calls.</li>
              </ul>
              {/* <span className="ai-badge">● Generated by AI</span> */}
            </div>
          </div>
        </div>

        <button className="start-chat-btn">+ Start New Chat</button>
      </main>
    </div>
  );
};

export default Home;